### ISSUE TITLE
Support PDF views in Chrome

### ISSUE THREAD

**Issue by simonwilson1985** [wswebcreation/wdio-image-comparison-service#15]
> **NOTE: Be aware of the fact that this module is only a plugin that provides all functionality from [`webdriver-image-comparison`](https://github.com/wswebcreation/webdriver-image-comparison). So please check if this is a feature request for this plugin or for `webdriver-image-comparison`.**

**Is your feature request related to a problem? Please describe.**
We use the pdf viewer in Chrome to check on some communications that are sent from our company. Using the saveFullPageScreen function it still cuts off the bottom of the page and shows the scroll bar.

**Describe the solution you'd like**
It would be nice to have it screenshot the full page without the scroll bar and, if possible, the "voids" either side of the PDF content

**Describe alternatives you've considered**
Just experimenting at the moment but a workaound could be to scroll and take another screenshot. ie. save multiple shots per PDF

**Additional context**

![image](https://user-images.githubusercontent.com/39986797/64947460-edd90080-d86c-11e9-9713-a433055dc65f.png)

**Comment by wswebcreation** [comment]
This also needs to be solved in https://github.com/wswebcreation/webdriver-image-comparison

**Comment by wswebcreation** [comment]
Hi @simonwilson1985 

I know this was a long time ago, but I've been checking this and I can't really find a way to do this. The full page screenshot works on the height of the app that is opened in the browser. A PDF is put into a `embeded` element which always has the viewport height. This means that we can't get the full page scroll height meaning it will only take a screenshot of the viewport, in spite of the fact that the pdf might have multiple pages.

Because I can't do it know I need to close this issue, sorry
