### ISSUE TITLE
stale element

### ISSUE THREAD

**Issue by tuan91** [wswebcreation/wdio-image-comparison-service#7]
**Environment :**
 - Node.js version: 10.15.1
 - NPM version: 6.4.1
 - Browser name and version: [e.g. Chrome 68]
 - Platform name and version: [e.g. Windows 10]
 - WebdriverIO version: 5.11.0
 - wdio-image-comparison-service version: 1.3.0

**Describe the bug**
Hi, my test fails. According to the staketrace the element is not attached to the page document, can you help me?

**To Reproduce**
clone my repositorie:
https://github.com/tuan91/wdio_stale_element

**Log**
```
stale element reference: element is not attached to the page document
  (Session info: chrome=74.0.3729.136)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 3.19.8-100.fc20.x86_64 x86_64)
```

**Comment by wswebcreation** [comment]
Hi @tuan91 

Just checking, is this only happening with the image comparison module?

**Comment by tuan91** [comment]
Hi @wswebcreation 
and yes it dosen't work only with image comparison module. 
The tracestack points out the method "checkElement".

**Comment by tuan91** [comment]
Hi @wswebcreation 
is there already a solution?

**Comment by wswebcreation** [comment]
Checking this one now and what I see is the following

At line 9 of your code 

  ```js
  const successlayercontent = $('.layer.js-layer.layer-add-to-cart.js-layer-add-to-cart > div');
  ``` 
the element already gets an elementID. This is the ID of the element when it is hidden.

Your check on line 21 checks 
```js
browser.waitUntil(() => {return successlayercontent.isExisting();}, 'Element doesnt exist');
``` 
checks with the same ID if the element exists and it will always return true, because the element was already existing in the dom

In the meantime the element changed state, meaning it got visible, and it looks like the element got a new elementID, because if you do this (asking for the latest elementID)

```js
browser.checkElement($('.layer.js-layer.layer-add-to-cart.js-layer-add-to-cart > div'), 'successlayer', {});
```

it works, see below

![Mobile-successlayer-463x925](https://user-images.githubusercontent.com/11979740/62003825-1a9a5280-b11d-11e9-8c1e-4cac2c4ca0a7.png)

I need to ask the guys from WebdriverIO why it _cashes_ the ID, this module needs to have the latest ID which is used for getting properties of the element based on a JS injection.

**Comment by tuan91** [comment]
hi @wswebcreation 
thanks for your Feedback!

I have several tests where I test the "successlayer" and there it worked without the method "waituntil". Only in this test, it did not work, so I thought check the elementID again. Unfortunately it does not work either.

Normally, the elementID does not change, it also works for other tests. I do not understand why the elementID is changing right now.

I have now accepted your change and unfortunately it still does not work.

**Comment by wswebcreation** [comment]
>  have now accepted your change and unfortunately it still does not work.

Hmm, when I run it it works, as you can see in the screenshot
